### ISSUE TITLE
Question about more than one person on a video.

### ISSUE THREAD

**Issue by jxchong77** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#1]
Hi, Im new to machine learning if im sorry if I asked any weird question, but how do you guys manage when there are one or more faces in a video, where FF++ fake have only one manipulated face when there are more than one faces in a scene. Thank you in advance!

**Comment by abhishekju06** [comment]
how to get the pre trained model? Please help

**Comment by davide-coccomini** [comment]
Hi. In our cases, as explained in the paper, we separate the faces and obtain different predictions for each one of them. If one or more of the faces are classified as fake, the whole video is fake. So, for example, if you have a video with 3 frames and in each frame, you have two people, with our system you will obtain:
Frame 0: 
  - Person 0: Fake
  - Person 1: Real
Frame 1: 
  - Person 0: Fake
  - Person 1: Fake
Frame 2: 
  - Person 0: Fake
  - Person 1: Real

Video-Level classifications:
    - Person 0: Fake (since the majority are fake [2/3])
    - Person 1: Real (since the majority are real [2/3])

Video is classified as fake since Person 0 is fake.

This is a simplification but you can find more information about it in the paper: 
https://arxiv.org/abs/2107.02612



For the pretrained model, I will publish it as soon as possible.
