### ISSUE TITLE
Grouping of faces corresponding to same person for inference

### ISSUE THREAD

**Issue by Ankit2527** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#40]
Hi @davide-coccomini, I see that in test.py file for inference, you group the faces corresponding to each person using the index in the filename of each bounding box. Is that correct? Or is there any other thing that you have added in the code for grouping bbox corresponding to each person before feeding into the model for prediction?

```
# Group the faces with the same index, reduce probabiity to skip some faces in the same video 
for path in frames_paths:
    for i in range(0,3): # Consider up to 3 faces per video
        if "_" + str(i) in path:
            if i not in frames_paths_dict.keys():
                frames_paths_dict[i] = [path]
            else:
                frames_paths_dict[i].append(path)
```

**Comment by davide-coccomini** [comment]
In this work, since the clustering step and multi-identity management were not the main focus, we just grouped based on the index given by the face detector. This is obviously not the best way to do that in terms of the quality of the result, even if it is a very cheap way to manage multi identities. If you are looking for a more advanced way to preprocess the videos and obtain quality multi-identity classification I suggest you see our recent work on that:
https://github.com/davide-coccomini/MINTIME-Multi-Identity-size-iNvariant-TIMEsformer-for-Video-Deepfake-Detection

**Comment by Ankit2527** [comment]
@davide-coccomini Thank you for your quick response. I suspected the same, as I tried manually using single videos at a time, and saw that the index were not consistent (not always in a minority of cases) with the faces corresponding to the same person.

**Comment by davide-coccomini** [comment]
Absolutely, the ideal would be to do similarity clustering, you can find code to do this on the MINTIME repository I linked above. In that repository and in the dedicated paper we also addressed, among others, the problem of multiple identities and how to handle them effectively.

**Comment by Ankit2527** [comment]
Thank you @davide-coccomini for your help and quick response!

**Comment by davide-coccomini** [comment]
No problem, if you need anything else, let me know!
